# Standards: 1.2
---
- name: Create required dirs
  loop:
    - /etc/systemd/system/logstash.service.d
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - elastiflow

- name: Fetch source archive
  unarchive:
    src: "{{ elastiflow_download }}"
    dest: /usr/share
    remote_src: True
    owner: root
    group: root
    creates: "/usr/share/elastiflow-{{ elastiflow_version }}"
  tags:
    - elastiflow

- name: Find enabled configs
  register: elastiflow_enabled_configs_find
  find:
    paths: "/usr/share/elastiflow-{{ elastiflow_version }}/logstash/elastiflow/conf.d"
    patterns: "*.conf"
  tags:
    - elastiflow

- name: Fact enabled configs
  set_fact:
    elastiflow_enabled_configs: "{{ elastiflow_enabled_configs_find.files | map(attribute='path') | map('basename') | map('regex_replace', '^([a-zA-Z0-9_-]+).*', '\\1') }}"
  tags:
    - elastiflow

- name: Find disabled configs
  register: elastiflow_disabled_configs_find
  find:
    paths: "/usr/share/elastiflow-{{ elastiflow_version }}/logstash/elastiflow/conf.d"
    patterns: "*.disabled"
  tags:
    - elastiflow

- name: Fact disabled configs
  set_fact:
    elastiflow_disabled_configs: "{{ elastiflow_disabled_configs_find.files | map(attribute='path') | map('basename') | map('regex_replace', '^([a-zA-Z0-9_-]+).*', '\\1') }}"
  tags:
    - elastiflow

- name: Enable defined configs
  notify:
    - Restart logstash
  loop: "{{ elastiflow_configs }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.name in elastiflow_disabled_configs and item.state | default('enable') == 'enable'
  command:
    cmd: "mv {{ item.name }}.logstash.conf.disabled {{ item.name }}.logstash.conf"
    chdir: "/usr/share/elastiflow-{{ elastiflow_version }}/logstash/elastiflow/conf.d"
    creates: /usr/share/elastiflow-{{ elastiflow_version }}/logstash/elastiflow/conf.d/{{ item.name }}.logstash.conf
  tags:
    - elastiflow

- name: Disable defined configs
  notify:
    - Restart logstash
  loop: "{{ elastiflow_configs }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.name in elastiflow_enabled_configs and item.state | default('enable') == 'disable'
  command:
    cmd: "mv {{ item.name }}.logstash.conf {{ item.name }}.logstash.conf.disabled"
    chdir: "/usr/share/elastiflow-{{ elastiflow_version }}/logstash/elastiflow/conf.d"
    creates: /usr/share/elastiflow-{{ elastiflow_version }}/logstash/elastiflow/conf.d/{{ item.name }}.logstash.conf.disabled
  tags:
    - elastiflow

- name: Symlink logstash config
  notify:
    - Restart logstash
  file:
    src: "/usr/share/elastiflow-{{ elastiflow_version }}/logstash/elastiflow"
    dest: /etc/logstash/elastiflow
    state: link
  tags:
    - elastiflow

- name: Write service override
  notify:
    - Restart logstash
  template:
    src: override.j2
    dest: /etc/systemd/system/logstash.service.d/elastiflow.conf
    owner: root
    group: root
    mode: u=rw,g=rw,o=
  tags:
    - elastiflow

- name: Write profile variables
  notify:
    - Restart logstash
  template:
    src: profile.j2
    dest: /etc/profile.d/elastiflow.sh
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=rx
  tags:
    - elastiflow

...
